const registrationModel = [
  {
    element: "text",
    name: "vorname",
    label: "Vorname Baby",
    type: "textInputHalf",
    half: true,
    defaultValue: "",
    id: "contactform-name",
    helperText: " ",
    minLength: 2,
    validation: "lengthError",
    error: false,
  },

  {
    element: "text",
    name: "nachname",
    label: "Nachname Baby",
    type: "textInputHalf",
    half: true,
    defaultValue: "",
    id: "contactform-lastname",
    helperText: " ",
    minLength: 2,
    validation: "lengthError",
    error: false,
  },

  {
    element: "text",
    name: "strasse",
    label: "Strasse",
    type: "textInputHalf",
    half: true,
    defaultValue: "",
    id: "contactform-street",
    helperText: " ",
    minLength: 2,
    validation: "lengthError",
    error: false,
  },

  {
    element: "number",
    name: "plz",
    label: "PLZ",
    type: "numberInputStyle",
    style: { width: "22.5%" },
    id: "contactform-postal",
    defaultValue: "",
    helperText: " ",
    minLength: 4,
    validation: "lengthError",
    error: false,
  },

  {
    element: "text",
    name: "ort",
    label: "Ort",
    type: "textReadOnly",
    id: "place-compare",
    defaultValue: "",
    helperText: " ",
    minLength: 2,
    validation: "lengthError",
    error: false,
  },

  {
    element: "number",
    name: "telefon",
    label: "Telefon",
    type: "textInputHalf",
    half: true,
    id: "contactform-tel",
    defaultValue: "",
    helperText: " ",
    minLength: 10,
    validation: "phoneError",
    error: false,
  },

  {
    element: "email",
    name: "email",
    label: "E-Mail",
    type: "textInputHalf",
    half: true,
    id: "contactform-email",
    defaultValue: "",
    helperText: " ",
    validation: "emailError",
    error: false,
  },

  {
    element: "text",
    name: "geburtsdatum",
    label: "Voraussichtlicher geburtstermin",
    type: "datePicker",
    half: true,
    id: "contactform-appointment",
    defaultValue: "",
    helperText: " ",
    validation: "dateError",
    error: false,
  },

  {
    element: "select",
    name: "persons",
    label: "Anzahl Personen im Haushalt",
    type: "selectInput",
    style: { width: "48%" },
    id: "persons-index",
    defaultValue: "",
    helperText: " ",
    validation: "selectError",
    error: false,
    options: [1, 2, 3, 4, 5, 6, 7, 8, 9],
  },
]

export default registrationModel
