const registrationModel = [
  {
    element: "text",
    name: "vorname",
    label: "Vorname",
    type: "textInput",
    half: true,
    defaultValue: "",
    id: "name-index",
    helperText: " ",
    minLength: 2,
    validation: "lengthError",
    error: false,
  },
  {
    element: "text",
    name: "nachname",
    label: "Nachname",
    type: "textInput",
    half: true,
    defaultValue: "",
    id: "lastname-index",
    helperText: " ",
    minLength: 2,
    validation: "lengthError",
    error: false,
  },

  {
    element: "text",
    name: "strasse",
    label: "Strasse",
    type: "textInput",
    half: true,
    defaultValue: "",
    id: "street-index",
    helperText: " ",
    minLength: 2,
    validation: "lengthError",
    error: false,
  },

  {
    element: "number",
    name: "telefon",
    label: "Telefon",
    type: "textInput",
    half: true,
    id: "phone-index",
    defaultValue: "",
    helperText: " ",
    minLength: 10,
    validation: "phoneError",
    error: false,
  },

  {
    element: "email",
    name: "email",
    label: "E-Mail",
    type: "textInput",
    half: true,
    id: "email-index",
    defaultValue: "",
    helperText: " ",
    validation: "emailError",
    error: false,
  },

  {
    element: "text",
    name: "geburtsdatum",
    label: "Geburtsdatum",
    type: "datePicker",
    half: true,
    id: "bdate-index",
    defaultValue: "",
    helperText: " ",
    validation: "dateError",
    error: false,
  },

  {
    element: "select",
    name: "persons",
    label: "Anzahl Personen im Haushalt",
    type: "inputFullWidth",
    id: "persons-index",
    defaultValue: "",
    helperText: " ",
    validation: "selectError",
    error: false,
    options: ["AA", "BB"],
  },
]

export default registrationModel
