const registrationModel = [
  {
    element: "select",
    name: "insurance",
    label: "Aktuelle Krankenkasse",
    type: "inputFullWidth",
    id: "insurance-compare",
    defaultValue: "",
    helperText: " ",
    validation: "selectError",
    error: false,
    options: [
      "Vorgeburt",
      "AMB",
      "Agrisano",
      "Aquilana",
      "Arcosana",
      "Assura",
      "Atupri",
      "Avanex",
      "Avenir",
      "Birchmeier",
      "CSS",
      "Compact",
      "Concordia",
      "ÖKK",
      "EGK",
      "EasySana",
      "Einsiedeln",
      "Flaachtal",
      "Galenos",
      "Glarner",
      "GroupeMutuel",
      "Helsana",
      "Ingenbohl",
      "Innova",
      "Intras",
      "KPT / CPT",
      "Klug",
      "Kmu",
      "Kolping",
      "Lumneziana",
      "LuzernerHinterland",
      "Philos",
      "Progrès",
      "Provita",
      "Rhenusana",
      "SLKK",
      "Sana24",
      "Sanagate",
      "Sanavals",
      "Sanitas",
      "Sansan",
      "Simplon",
      "Sodalis",
      "Steffisburg",
      "Stoffel",
      "Sumiswalder",
      "Supra",
      "Swica",
      "Sympany",
      "Turbenthal",
      "Visana",
      "Wädenswil",
    ],
  },

  {
    element: "number",
    name: "plz",
    label: "PLZ",
    type: "numberInputStyle",
    id: "postalcode-compare",
    defaultValue: "",
    helperText: " ",
    minLength: 4,
    validation: "lengthError",
    error: false,
  },

  {
    element: "text",
    name: "ort",
    label: "Ort",
    id: "place-compare",
    defaultValue: "",
    helperText: " ",
    minLength: 2,
    validation: "lengthError",
    error: false,
  },

  {
    element: "select",
    name: "ageGroup",
    label: "Altersgruppe",
    type: "selectInput",
    id: "age-compare",
    defaultValue: "",
    helperText: " ",
    validation: "selectError",
    error: false,
    options: ["0-18 Jahre", "19-25 Jahre", "ab 25 Jahre"],
  },
]

export default registrationModel
