const registrationModel = [
  {
    element: "text",
    name: "vorname",
    label: { de: "Vorname", en: "First Name", fr: "Prénom", it: "Nome" },
    type: "textInput",
    half: true,
    defaultValue: "",
    id: "name-index",
    helperText: " ",
    minLength: 2,
    validation: "lengthError",
    error: false,
  },
  {
    element: "text",
    name: "nachname",
    label: { de: "Nachname", en: "Last Name", fr: "Nom", it: "Cognome" },
    type: "textInput",
    half: true,
    defaultValue: "",
    id: "lastname-index",
    helperText: " ",
    minLength: 2,
    validation: "lengthError",
    error: false,
  },
  {
    element: "text",
    name: "strasse",
    label: { de: "Strasse", en: "Street/No.", fr: "Rue/No", it: "Via/N." },
    type: "textInput",
    half: true,
    defaultValue: "",
    id: "street-index",
    helperText: " ",
    minLength: 2,
    validation: "lengthError",
    error: false,
  },
  {
    element: "number",
    name: "plz",
    label: {
      de: "PLZ",
      en: "Postcode",
      fr: "NPA",
      it: "NPA",
    },
    type: "numberInputStyle",
    style: { width: "22.5%" },
    id: "postalcode-compare",
    defaultValue: "",
    helperText: " ",
    minLength: 4,
    validation: "lengthError",
    error: false,
  },

  {
    element: "text",
    name: "ort",
    label: {
      de: "Ort",
      en: "Town",
      fr: "Localité",
      it: "Località",
    },
    type: "textReadOnly",
    id: "place-compare",
    defaultValue: "",
    helperText: " ",
    minLength: 2,
    validation: "lengthError",
    error: false,
  },

  {
    element: "number",
    name: "telefon",
    label: { de: "Telefon", en: "Phone", fr: "Téléphone", it: "Telefono" },
    type: "textInput",
    half: true,
    id: "phone-index",
    defaultValue: "",
    helperText: " ",
    minLength: 10,
    validation: "phoneError",
    error: false,
  },

  {
    element: "email",
    name: "email",
    label: { de: "E-Mail", en: "E-Mail", fr: "E-Mail", it: "E-Mail" },
    type: "textInput",
    half: true,
    id: "email-index",
    defaultValue: "",
    helperText: " ",
    validation: "emailError",
    error: false,
  },

  {
    element: "text",
    name: "geburtsdatum",
    label: {
      de: "Geburtsdatum",
      en: "Date of birth",
      fr: "Date de naissance",
      it: "Data di nascita",
    },
    type: "datePicker",
    half: true,
    id: "bdate-index",
    defaultValue: "",
    helperText: " ",
    validation: "dateError",
    error: false,
  },

  {
    element: "select",
    name: "persons",
    label: {
      de: "Anzahl Personen im Haushalt",
      en: "Number of persons in household",
      fr: "Nombre de personnes dans le ménage",
      it: "Numero di persone in famiglia",
    },
    type: "selectInput",
    style: { width: "48%" },
    id: "persons-index",
    defaultValue: "",
    helperText: " ",
    validation: "selectError",
    error: false,
    options: ["AA", "BB"],
  },

  {
    element: "select",
    name: "insurance",
    label: {
      de: "Aktuelle Krankenkasse",
      en: "Current health insurance",
      fr: "Caisse d'assurance maladie actuelle",
      it: "Assicurazione sanitaria corrente",
    },
    type: "inputFullWidth",
    id: "contactform-index",
    defaultValue: "",
    helperText: " ",
    validation: "selectError",
    error: false,
    options: [
      "Vorgeburt",
      "AMB",
      "Agrisano",
      "Aquilana",
      "Arcosana",
      "Assura",
      "Atupri",
      "Avanex",
      "Avenir",
      "Birchmeier",
      "CSS",
      "Compact",
      "Concordia",
      "ÖKK",
      "EGK",
      "EasySana",
      "Einsiedeln",
      "Flaachtal",
      "Galenos",
      "Glarner",
      "GroupeMutuel",
      "Helsana",
      "Ingenbohl",
      "Innova",
      "Intras",
      "KPT / CPT",
      "Klug",
      "Kmu",
      "Kolping",
      "Lumneziana",
      "LuzernerHinterland",
      "Philos",
      "Progrès",
      "Provita",
      "Rhenusana",
      "SLKK",
      "Sana24",
      "Sanagate",
      "Sanavals",
      "Sanitas",
      "Sansan",
      "Simplon",
      "Sodalis",
      "Steffisburg",
      "Stoffel",
      "Sumiswalder",
      "Supra",
      "Swica",
      "Sympany",
      "Turbenthal",
      "Visana",
      "Wädenswil",
    ],
  },

  {
    element: "textarea",
    name: "teaxtarea-index",
    label: {
      de: "Nachricht",
      en: "Message",
      fr: "Ma requête",
      it: "La mia richiesta",
    },
    type: "textarea",
    style: { width: "100%" },
    id: "nachricht-index",
    defaultValue: "",
    helperText: " ",
  },
]

export default registrationModel
