const registrationModel = [
  {
    element: "text",
    name: "vorname",
    label: "Vorname",
    type: "textInput",
    half: true,
    defaultValue: "",
    id: "name-index",
    helperText: " ",
    minLength: 2,
    validation: "lengthError",
    error: false,
  },
  {
    element: "text",
    name: "nachname",
    label: "Nachname",
    type: "textInput",
    half: true,
    defaultValue: "",
    id: "lastname-index",
    helperText: " ",
    minLength: 2,
    validation: "lengthError",
    error: false,
  },
  {
    element: "text",
    name: "strasse",
    label: "Strasse",
    type: "textInput",
    half: true,
    defaultValue: "",
    id: "street-index",
    helperText: " ",
    minLength: 2,
    validation: "lengthError",
    error: false,
  },
  {
    element: "number",
    name: "plz",
    label: "PLZ",
    type: "numberInputStyle",
    style: { width: "22.5%" },
    id: "postalcode-compare",
    defaultValue: "",
    helperText: " ",
    minLength: 4,
    validation: "lengthError",
    error: false,
  },

  {
    element: "text",
    name: "ort",
    label: "Ort",
    type: "textReadOnly",
    id: "place-compare",
    defaultValue: "",
    helperText: " ",
    minLength: 2,
    validation: "lengthError",
    error: false,
  },

  {
    element: "number",
    name: "telefon",
    label: "Telefon",
    type: "textInput",
    half: true,
    id: "phone-index",
    defaultValue: "",
    helperText: " ",
    minLength: 10,
    validation: "phoneError",
    error: false,
  },

  {
    element: "email",
    name: "email",
    label: "E-Mail",
    type: "textInput",
    half: true,
    id: "email-index",
    defaultValue: "",
    helperText: " ",
    validation: "emailError",
    error: false,
  },

  {
    element: "text",
    name: "geburtsdatum",
    label: "Geburtsdatum",
    type: "datePicker",
    half: true,
    id: "bdate-index",
    defaultValue: "",
    helperText: " ",
    validation: "dateError",
    error: false,
  },

  {
    element: "select",
    name: "persons",
    label: "Anzahl Personen im Haushalt",
    type: "selectInput",
    style: { width: "48%" },
    id: "persons-index",
    defaultValue: "",
    helperText: " ",
    validation: "selectError",
    error: false,
    options: ["AA", "BB"],
  },

  {
    element: "select",
    name: "insurance",
    label: "Aktuelle Krankenkasse",
    type: "inputFullWidth",
    id: "contactform-index",
    defaultValue: "",
    helperText: " ",
    validation: "selectError",
    error: false,
    options: [
      "Vorgeburt",
      "AMB",
      "Agrisano",
      "Aquilana",
      "Arcosana",
      "Assura",
      "Atupri",
      "Avanex",
      "Avenir",
      "Birchmeier",
      "CSS",
      "Compact",
      "Concordia",
      "ÖKK",
      "EGK",
      "EasySana",
      "Einsiedeln",
      "Flaachtal",
      "Galenos",
      "Glarner",
      "GroupeMutuel",
      "Helsana",
      "Ingenbohl",
      "Innova",
      "Intras",
      "KPT / CPT",
      "Klug",
      "Kmu",
      "Kolping",
      "Lumneziana",
      "LuzernerHinterland",
      "Philos",
      "Progrès",
      "Provita",
      "Rhenusana",
      "SLKK",
      "Sana24",
      "Sanagate",
      "Sanavals",
      "Sanitas",
      "Sansan",
      "Simplon",
      "Sodalis",
      "Steffisburg",
      "Stoffel",
      "Sumiswalder",
      "Supra",
      "Swica",
      "Sympany",
      "Turbenthal",
      "Visana",
      "Wädenswil",
    ],
  },

  {
    element: "textarea",
    name: "teaxtarea-index",
    label: "Nachricht",
    type: "textarea",
    style: { width: "100%" },
    id: "nachricht-index",
    defaultValue: "",
    helperText: " ",
  },
]

export default registrationModel
